// examples/languages/svelte/src/App.svelte
<script lang="ts">
  import welcome from "./assets/svelte-welcome.webp";
  import Header from "./lib/Header.svelte";
  import welcome_fallback from "./assets/svelte-welcome.png";
  import "./styles.css";
  import CodatLink from "./lib/CodatLink.svelte";
  import type {
    ConnectionCallbackArgs,
    ErrorCallbackArgs,
  } from "https://link-sdk.codat.io";

  let modalOpen = false;
  let companyId = "";

  const onConnection = (connection: ConnectionCallbackArgs) =>
    alert(`On connection callback - ${connection.connectionId}`);
  const onClose = () => (modalOpen = false);
  const onFinish = () => alert("On finish callback");
  const onError = (error: ErrorCallbackArgs) =>
    alert(`On error callback - ${error.message}`);
</script>

<div class="app">
  <Header />
  <main>
    <span class="welcome">
      <picture>
        <source srcset={welcome} type="image/webp" />
        <img src={welcome_fallback} alt="Welcome" />
      </picture>
    </span>
    <h1>
      <a
        target="_blank"
        rel="noreferrer"
        href="https://github.com/codatio/sdk-link/blob/main/examples/svelte/README.md"
      >
        Link SDK X Svelte
      </a>
    </h1>
    <p>An example of embedding Link SDK within a Svelte App</p>
    <div>
      <ol>
        <li>
          <a
            href="https://github.com/codatio/sdk-link/tree/main#create-a-new-company"
            target="_blank"
            rel="noreferrer"
          >
            Create a company
          </a>
        </li>
        <li>Paste the company ID below</li>
      </ol>
      <div class="input-wrapper">
        <input
          bind:value={companyId}
          placeholder="Provide a valid company ID"
        />
        <button
          on:click={() => {
            modalOpen = true;
          }}>Start authing</button
        >
      </div>
    </div>
    {#if modalOpen}
      <div class="modal-wrapper">
        <CodatLink {companyId} {onConnection} {onClose} {onError} {onFinish} />
      </div>
    {/if}
  </main>
</div>

<style>
  .app {
    display: flex;
    flex-direction: column;
    min-height: 100vh;
  }

  h1 {
    margin: 0;
  }

  main {
    flex: 0.6;
    display: flex;
    flex-direction: column;
    justify-content: start;
    align-items: center;
  }

  .welcome {
    display: block;
    position: relative;
    width: 100%;
    max-width: 1200px;
    margin-top: 20px;
    padding: 0 0 min(200px, calc(100% * 495 / 2048)) 0;
  }

  .welcome img {
    position: absolute;
    width: 100%;
    height: 100%;
    top: 0;
    display: block;
  }
  .modal-wrapper {
    align-items: center;
    box-sizing: border-box;
    display: flex;
    justify-content: center;
    position: fixed;
    inset: 0;
  }
</style>

// examples/vue/src/App.vue
<script setup lang="ts">
import CodatLinkComponent from './components/CodatLinkComponent.vue'
import { ref } from 'vue'
import type { ConnectionCallbackArgs, ErrorCallbackArgs } from 'https://link-sdk.codat.io'

const companyId = ref('')
const modalOpen = ref(false)

const handleCloseModal = () => {
  modalOpen.value = false
}

const handleOnConnection = (connection: ConnectionCallbackArgs) => {
  alert(`On connection callback - ${connection.connectionId}`)
}

const handleOnClose = () => {
  handleCloseModal()
}

const handleOnFinish = () => {
  alert('On finish callback')
  handleCloseModal()
}

const handleOnError = (error: ErrorCallbackArgs) => {
  alert(`On error callback -${error.message}`)
  handleCloseModal()
}
</script>

<template>
  <main class="main">
    <header>
      <img alt="Vue logo" class="logo" src="./assets/logo.svg" width="125" height="125" />
      <h1 class="title">
        <a target="_blank" rel="noreferrer" href="https://github.com/codatio/sdk-link/tree/main/examples/vue/README.md">
          Link SDK X Vue
        </a>
      </h1>
    </header>
    <div class="content">
      <p>An example of embedding Link SDK within a brand new create-vue project</p>
      <ol>
        <li>
          <a href="https://github.com/codatio/sdk-link/tree/main#create-a-new-company" target="_blank" rel="noreferrer">
            Create a company
          </a>
        </li>
        <li>Paste the company ID below</li>
      </ol>
      <input type="text" v-model="companyId" placeholder="Provide a valid company ID" />
      <button @click="modalOpen = !modalOpen">
        {{ modalOpen ? 'Exit' : 'Start authing' }}
      </button>
    </div>
    <div v-if="modalOpen" class="modalWrapper">
      <CodatLinkComponent :company-id="companyId" :on-connection="handleOnConnection" :on-close="handleOnClose"
        :on-finish="handleOnFinish" :on-error="handleOnError" />
    </div>
  </main>
</template>

<style scoped>
.main {
  display: flex;
  flex-direction: column;
  align-items: center;
  padding: 6rem;
  gap: 1rem;
  min-height: 100vh;
  box-sizing: border-box;
}

.logo {
  display: block;
  margin: 0 auto 2rem;
}

.content {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 0.5rem;
}

.modalWrapper {
  align-items: center;
  box-sizing: border-box;
  display: flex;
  justify-content: center;
  position: fixed;
  inset: 0;
  z-index: 2;
}
</style>
