// examples/svelte/src/lib/CodatLink.svelte
<script lang="ts">
  import type {
    ConnectionCallbackArgs,
    ErrorCallbackArgs,
  } from "https://link-sdk.codat.io";

  export let companyId: string;
  export let onConnection: (connection: ConnectionCallbackArgs) => void;
  export let onClose: () => void;
  export let onFinish: () => void;
  export let onError: (error: ErrorCallbackArgs) => void;

  const CodatLinkAction = (node: HTMLElement) => {
    const target = node;
    import("https://link-sdk.codat.io").then(({ CodatLink }) => {
      new CodatLink({
        target,
        props: {
          companyId,
          onConnection,
          onClose,
          onFinish,
          onError,
        },
      });
    });
  };
</script>

<!-- Inline styles suggest recommended dimensions -->
<div style="width: 460px; height:840px;  maxHeight: 95%" use:CodatLinkAction />

// examples/vue/src/components/CodatLinkComponent.vue
<script setup lang="ts">
import type { ConnectionCallbackArgs, ErrorCallbackArgs } from 'https://link-sdk.codat.io'

import { ref, onMounted } from 'vue'

const props = defineProps<{
  companyId: string
  onConnection: (args: ConnectionCallbackArgs) => void
  onError: (args: ErrorCallbackArgs) => void
  onClose: () => void
  onFinish: () => void
}>()

const target = ref()

onMounted(() => {
  if (target.value && target.value.children.length === 0) {
    import('https://link-sdk.codat.io').then(({ CodatLink }) => {
      new CodatLink({
        target: target.value,
        props: {
          companyId: props.companyId,
          onConnection: props.onConnection,
          onClose: props.onClose,
          onFinish: props.onFinish,
          onError: props.onError
        }
      })
    })
  }
})
</script>

<template>
  <div class="wrapper" ref="target"></div>
</template>

<style scoped>
.wrapper {
  width: 460px;
  height: 840px;
  max-height: 95%;
}
</style>
