// snippets/CodatLink.tsx
import {
  CodatLink,
  ConnectionCallbackArgs,
  ErrorCallbackArgs,
} from "https://link-sdk.codat.io";
import React, { useEffect, useState } from "react";

export interface CodatLinkProps {
  companyId: string;
  onConnection: (args: ConnectionCallbackArgs) => void;
  onError: (args: ErrorCallbackArgs) => void;
  onClose: () => void;
  onFinish: () => void;
}

export const CodatLinkReact: React.FC<CodatLinkProps> = (props) => {
  const { companyId, onConnection, onError, onClose, onFinish } = props;

  const [componentMount, setComponentMount] = useState<HTMLDivElement | null>(
    null
  );

  useEffect(() => {
    const target = componentMount;
    if (target && target.children.length === 0) {
      new CodatLink({
        target,
        props: {
          companyId,
          onConnection,
          onClose,
          onFinish,
          onError,
        },
      });
    }
    // CodatLink does not support changing props after initialisation.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [componentMount]);

  return (
    <div
      className="App"
      style={{
        // CodatLink will take up 100% of the container width and height.
        // We recommend a size of 460px x 840px.
        width: "460px",
        height: "840px",
      }}
      data-testId="test"
      ref={setComponentMount}
    ></div>
  );
};

// examples/vue/src/components/CodatLinkComponent.vue
<script setup lang="ts">
import type { ConnectionCallbackArgs, ErrorCallbackArgs } from 'https://link-sdk.codat.io'

import { ref, onMounted } from 'vue'

const props = defineProps<{
  companyId: string
  onConnection: (args: ConnectionCallbackArgs) => void
  onError: (args: ErrorCallbackArgs) => void
  onClose: () => void
  onFinish: () => void
}>()

const target = ref()

onMounted(() => {
  if (target.value && target.value.children.length === 0) {
    import('https://link-sdk.codat.io').then(({ CodatLink }) => {
      new CodatLink({
        target: target.value,
        props: {
          companyId: props.companyId,
          onConnection: props.onConnection,
          onClose: props.onClose,
          onFinish: props.onFinish,
          onError: props.onError
        }
      })
    })
  }
})
</script>

<template>
  <div class="wrapper" ref="target"></div>
</template>

<style scoped>
.wrapper {
  width: 460px;
  height: 840px;
  max-height: 95%;
}
</style>
